repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: fix-byte-order-marker
    -   id: check-docstring-first
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-ast
    -   id: requirements-txt-fixer

# General Project code formatter.
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black

# Sorts python imports.
-   repo: https://github.com/PyCQA/isort
    # Note - on black update blacken-docs pin should also be updated.
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ['--profile=black']


# Formats python docstrings.
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter

# Used to detect unintentionally unused code.
-   repo: https://github.com/asottile/dead
    rev: v1.5.2
    hooks:
    -   id: dead
        args: [
            '--exclude=conf.py'  # Ignore the sphinx config as this is used by an external tool.
        ]

# Lint code in pre-commit env, note: This ignores import checks.
-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.3
    hooks:
    -   id: pylint
        args: [
            '--disable=E0401',  # Ignore imports when not running in a local env.
            '--disable=R0903',  # Class are built on interfaces so too few methods isn't important.
            "--disable=R0902",
        ]

# Lint docstrings.
-   repo: https://github.com/PyCQA/pydocstyle
    # Waiting for a 3.10 release on pypi
    rev: "6.3.0"
    hooks:
    -   id: pydocstyle
        additional_dependencies:
            # TOML support only added natively in python 3.11
            - toml
