language: python

matrix:
  include:
  - os: linux
    dist: xenial
  - os: linux
    dist: bionic
  - os: osx
    language: generic

addons:
  apt:
    packages:
    - clang
    - clang-format
    - clang-tidy
    - uncrustify
    - cppcheck
    - iwyu
    # Required for iwyu
    - llvm-9-dev
    - libclang-9-dev
    - clang-9
script: "./tests/run_tests.sh"
