name: pre-commit-hooks testing
on: [push]
jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install 6 hooks (not oclint on windows), python, pip
        run: choco install llvm uncrustify cppcheck iwyu python3 python3-pip -y --no-progress
      - name: Install pip dependencies
        run: pip install cpplint pytest black
      - name: Run tests
        run: pytest -x -vvv
