name: pre-commit-hooks testing
on: [push]
jobs:
  build:
    runs-on: [macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add llvm utils clang-format and clang-tidy to path
        run: echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
      - name: Reinstall llvm to help macos find stdio.h
        run: brew reinstall llvm
      - name: Install 4 hooks, python3, llvm 12.0.1 already installed which includes clang-tidy, clang-format
        run: brew install llvm uncrustify cppcheck oclint iwyu python3
      - name: Install C/C++ libraries with xcode, latest
        run: |
          sudo rm -rf /Library/Developer/CommandLineTools
          xcode-select --install
      - name: Install pip dependencies
        run: pip3 install cpplint pytest pre-commit
      - name: Install hooks locally
        run: pip3 install .
      - name: Get command versions
        run: |
          clang-format --version
          clang-tidy --version
          cppcheck --version
          cpplint --version
          include-what-you-use --version
          oclint --version
      - name: Get python library versions
        run: |
          pytest --version
          pre-commit --version
      - name: Run tests
        run: pytest -x -vvv
