name: test windows latest
on: [push]
jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install python3.8
        run: choco install python --version=3.8.10 -y --no-progress
      - name: Install 5 hooks (not oclint, iwyu on windows), python3
        run: choco install llvm uncrustify cppcheck -y --no-progress
      - name: Update paths (see https://stackoverflow.com/questions/60169752)
        run: echo "C:\Program Files\LLVM\bin;C:\ProgramData\chocolatey\lib\uncrustify\tools;C:\Program Files\Cppcheck;C:\Python39" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Check installations
        run: |
          clang-format --version
          clang-tidy --version
          uncrustify --version
          cppcheck --version
          python3 --version
      - name: Install pip dependencies
        run: pip3 install cpplint pytest black pre-commit
      - name: Install hooks locally
        run: pip3 install .
      - name: Get command versions
        run: |
          clang-format --version
          clang-tidy --version
          cppcheck --version
          cpplint --version
      - name: Get python library versions
        run: |
          pytest --version
          pre-commit --version
      - name: Run tests using installed python3.8
        run: C:\hostedtoolcache\windows\Python\3.8.10\x64\python-3.8.10-amd64.exe -m pytest -x -vvv
