name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  run-test:
    name: ${{ matrix.python-version }}-${{ matrix.build-type }}-${{ matrix.architecture }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        architecture:
          - x64
          - x86

        exclude:
          # linux does not have x86 python.
          - os: "ubuntu-latest"
            architecture: x86

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pytest coverage
      - name: Run tests
        run: |
          cd tests/
          python -m pytest -s .
